services:
  ad-task-3-php:
    build:
      context: .
    container_name: ad-task-3-php-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: ad-task-3-php-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: adtask3
    ports:
      - "23567:27017"
    volumes:
      - ad-task-3-php-mongodb:/data/db

  postgresql:
    image: postgres:15
    container_name: ad-task-3-php-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adtask3
    ports:
      - "5555:5432"
    volumes:
      - ad-task-3-php-postgresql:/var/lib/postgresql/data

volumes:
  ad-task-3-php-mongodb:
    driver: local
  ad-task-3-php-postgresql:
    driver: local
